# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3a773c33eb105d09dfc396ecd71adb0c"
name = "Voice Search"
handle = "voice-search-3"
application_url = "https://cms-wb-considerations-anonymous.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "jassfeels.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://cms-wb-considerations-anonymous.trycloudflare.com/auth/callback",
  "https://cms-wb-considerations-anonymous.trycloudflare.com/auth/shopify/callback",
  "https://cms-wb-considerations-anonymous.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
